[server]
enableStaticServing = true

[theme]
primaryColor = "#1F2937"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#1F2937"
font = "sans serif"

[theme.sidebar]
primaryColor = "#22C55E"
backgroundColor = "#2a3647"
secondaryBackgroundColor = "#5e7aa1"
textColor = "#F9FAFB"

