[server]
enableStaticServing = true

[theme]
primaryColor = "#1F2937"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EEF7F0"
textColor = "#1F2937"
font = "sans serif"

[theme.sidebar]
primaryColor = "#1F2937"

